# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: windows-latest

steps:

- script: |
    python3 -m pip install --upgrade pip
    python3 -m pip install --upgrade git+https://github.com/sonntagsgesicht/auxilium
    python3 -m pip  install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python3 -m auxilium -e= test --security --quality --coverage
  displayName: 'auxilium test'
